#!/bin/bash

if [ "$1" == "remove" ] || [ "$1" == "purge" ]; then 

# removing config+database files should be performed only if user requested purge

	if [ "$1" == "purge" ]; then

		rm -fr /usr/local/share/autosub
		rm -fr /etc/autosub
                rm -f /etc/default/autosub

	fi

	true

fi
