#!/bin/bash

if [ $1 == "configure" ]; then

	if [ ! -d "/home/xbian/downloads" ]; then
		mkdir -p /home/xbian/downloads
	fi

	chmod 777 /home/xbian/downloads
	chown xbian:xbian /home/xbian/downloads

	if [ ! -d "/home/xbian/incomplete" ]; then
		mkdir -p /home/xbian/incomplete
	fi

	chmod 777 /home/xbian/incomplete
	chown xbian:xbian /home/xbian/incomplete

	if [ ! -d "/home/xbian/torrents" ]; then
		mkdir -p /home/xbian/torrents
	fi

	chmod 777 /home/xbian/torrents
	chown xbian:xbian /home/xbian/torrents

	if [ -f "/usr/local/etc/auto-sub/config.reuse" ]; then
		mv /usr/local/etc/auto-sub/config.properties /usr/local/etc/auto-sub/config.new;
		mv /usr/local/etc/auto-sub/config.reuse /usr/local/etc/auto-sub/config.properties;
	fi

	chmod 777 /usr/local/share/auto-sub
	chown -R xbian /usr/local/share/auto-sub
	chmod -R 777 /usr/local/etc/auto-sub


	/etc/init.d/autosub start &>/dev/null

fi
